package com.universite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EdtAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdtAllPropertiesEquals(Edt expected, Edt actual) {
        assertEdtAutoGeneratedPropertiesEquals(expected, actual);
        assertEdtAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdtAllUpdatablePropertiesEquals(Edt expected, Edt actual) {
        assertEdtUpdatableFieldsEquals(expected, actual);
        assertEdtUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdtAutoGeneratedPropertiesEquals(Edt expected, Edt actual) {
        assertThat(actual)
            .as("Verify Edt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdtUpdatableFieldsEquals(Edt expected, Edt actual) {
        assertThat(actual)
            .as("Verify Edt relevant properties")
            .satisfies(a -> assertThat(a.getIdEdt()).as("check idEdt").isEqualTo(expected.getIdEdt()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdtUpdatableRelationshipsEquals(Edt expected, Edt actual) {
        assertThat(actual)
            .as("Verify Edt relationships")
            .satisfies(a -> assertThat(a.getIdFiliere()).as("check idFiliere").isEqualTo(expected.getIdFiliere()));
    }
}
