package com.universite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeachingAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeachingAssignmentAllPropertiesEquals(TeachingAssignment expected, TeachingAssignment actual) {
        assertTeachingAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTeachingAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeachingAssignmentAllUpdatablePropertiesEquals(TeachingAssignment expected, TeachingAssignment actual) {
        assertTeachingAssignmentUpdatableFieldsEquals(expected, actual);
        assertTeachingAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeachingAssignmentAutoGeneratedPropertiesEquals(TeachingAssignment expected, TeachingAssignment actual) {
        assertThat(actual)
            .as("Verify TeachingAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeachingAssignmentUpdatableFieldsEquals(TeachingAssignment expected, TeachingAssignment actual) {
        assertThat(actual)
            .as("Verify TeachingAssignment relevant properties")
            .satisfies(a ->
                assertThat(a.getIdTeachingAssignment()).as("check idTeachingAssignment").isEqualTo(expected.getIdTeachingAssignment())
            )
            .satisfies(a -> assertThat(a.getAcademicYear()).as("check academicYear").isEqualTo(expected.getAcademicYear()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeachingAssignmentUpdatableRelationshipsEquals(TeachingAssignment expected, TeachingAssignment actual) {
        assertThat(actual)
            .as("Verify TeachingAssignment relationships")
            .satisfies(a -> assertThat(a.getIdTeacher()).as("check idTeacher").isEqualTo(expected.getIdTeacher()));
    }
}
