package com.universite.module.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DepartementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementAllPropertiesEquals(Departement expected, Departement actual) {
        assertDepartementAutoGeneratedPropertiesEquals(expected, actual);
        assertDepartementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementAllUpdatablePropertiesEquals(Departement expected, Departement actual) {
        assertDepartementUpdatableFieldsEquals(expected, actual);
        assertDepartementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementAutoGeneratedPropertiesEquals(Departement expected, Departement actual) {
        assertThat(actual)
            .as("Verify Departement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementUpdatableFieldsEquals(Departement expected, Departement actual) {
        assertThat(actual)
            .as("Verify Departement relevant properties")
            .satisfies(a -> assertThat(a.getIdDepartement()).as("check idDepartement").isEqualTo(expected.getIdDepartement()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementUpdatableRelationshipsEquals(Departement expected, Departement actual) {
        // empty method
    }
}
